version: '3.8'

services:
  chatbot:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: chatbot_app
    ports:
      - "5000:5000"
    env_file:
      - ../env/.env
    volumes:
      - ../logs:/app/logs
      - ../uploads:/app/uploads  # <--- aquí se guardarán las imágenes
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: chatbot_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: chatbotdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ngrok:
    image: ngrok/ngrok:latest
    container_name: chatbot_ngrok
    command: http chatbot:5000
    env_file:
      - ./ngrok.yml
    ports:
      - "4040:4040"
    depends_on:
      - chatbot

volumes:
  postgres_data:
